# Generated by Django 3.0.6 on 2020-05-14 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='owner',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='members',
            field=models.ManyToManyField(through='chat.ChatSessionMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsessionmember',
            name='chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.ChatSession'),
        ),
    ]
